export const ADD_HISTORY = "ADD_HISTORY";
export const ADD_EXPRESSION = "ADD_EXPRESSION";
export const SET_HISTORY_VISABILITY = "SET_HISTORY_VISABILITY";
export const CLEAN_HISTORY = "CLEAN_HISTORY";
export const TOOGLE_THEME = "TOOGLE_THEME";
export const SET_RESULT = "SET_RESULT";
export const SET_PREVIOUS_EXPRESSION = "SET_PREVIOUS_EXPRESSION";